CREATE TABLE TB_CLIENTE (
	
    ID_CLIENTE 			INT PRIMARY KEY AUTO_INCREMENT,
	NM_NOME 			VARCHAR(200),
    DS_EMAIL			VARCHAR(200),
    DS_TELEFONE			VARCHAR(16),
    DS_CPF				VARCHAR(150),
    DS_CNH				VARCHAR(150)
    
);


CREATE TABLE TB_TIPO_VEICULO (
	
    ID_TIPO_VEICULO		INT PRIMARY KEY AUTO_INCREMENT,
    DS_TIPO				VARCHAR(200)
    
);


CREATE TABLE TB_VEICULO (
	
    ID_VEICULO 			INT PRIMARY KEY AUTO_INCREMENT,
	ID_TIPO_VEICULO		INT				NOT NULL,
	DS_MODELO 			VARCHAR(200)  	NOT NULL,
    DS_MARCA			VARCHAR(15)		NOT NULL,
    NR_ANO				INT				NOT NULL,
    DS_PLACA			VARCHAR(150)	NOT NULL,
    
    FOREIGN KEY (ID_TIPO_VEICULO) REFERENCES TB_TIPO_VEICULO (ID_TIPO_VEICULO)
    
);

